name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build for Linux
        run: cargo build --release

      - name: Package Linux executable
        run: tar -czf nc-rust-linux.tar.gz -C target/release nc-rust

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build for Windows
        run: cargo build --release --target x86_64-pc-windows-gnu

      - name: Package Windows executable
        run: zip -r nc-rust-windows.zip target\release\nc-rust.exe

  release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Upload Linux release artifact
        uses: actions/upload-artifact@v2
        with:
          name: nc-rust-linux
          path: nc-rust-linux.tar.gz

      - name: Upload Windows release artifact
        uses: actions/upload-artifact@v2
        with:
          name: nc-rust-windows
          path: nc-rust-windows.zip
